export const actors = [
  {
    id: 1,
    user: {
      name: "John Doe",
      id: 1,
      public_hash: "",
      username: "",
      location: "",
      last_interaction: "",
      picture_small: "",
      picture_medium: "",
      picture_large: "",
      created_at: "",
      updated_at: "",
    },
    user_id: 1,
    service_id: "",
    payment_methods: [],
    headline: "",
    summary: "",
    favorite: false,
    additional_services: [],
    allow_bookings: false,
    membership_product_name: "",
    locations: [],
    relevant_sample: {
      file: "sample-file-1.mp3",
      id: 1,
      name: "",
      provider_id: 1,
      additional_info: "",
      display_order: [],
      is_approved: false,
      additional_services: [],
      languages: [],
      is_valid: false,
      service_id: "",
      created_at: "",
      updated_at: "",
      voice_types: [],
      voice_age_genders: [],
    },
    additional_details: "",
    languages: [],
    voice_age_genders: [],
    voice_types: [],
    recording_capabilities: [],
  },
  {
    id: 2,
    user: {
      name: "Jane Doe",
      id: 2,
      public_hash: "",
      username: "",
      location: "",
      last_interaction: "",
      picture_small: "",
      picture_medium: "",
      picture_large: "",
      created_at: "",
      updated_at: "",
    },
    user_id: 2,
    service_id: "",
    payment_methods: [],
    headline: "",
    summary: "",
    favorite: false,
    additional_services: [],
    allow_bookings: false,
    membership_product_name: "",
    locations: [],
    relevant_sample: {
      file: "",
      id: 2,
      name: "",
      provider_id: 2,
      additional_info: "",

      is_approved: false,
      additional_services: [],
      languages: [],
      is_valid: false,
      service_id: "",
      created_at: "",
      updated_at: "",
      voice_types: [],
      voice_age_genders: [],
      display_order: [],
    },
    additional_details: "",
    languages: [],
    voice_age_genders: [],
    voice_types: [],
    recording_capabilities: [],
  },
];
